version: "3.8"
services:

  be:
    image: zyonb/zd-be
    container_name: be
    ports:
      - 80:80
    networks:
      - spring-cloud-network
    depends_on:
      - postgresso

  postgresso:
    image: zyonb/zd-db
    container_name: db
    restart: always
    ports:
      - 7777:5432
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - postgvol:/var/lib/postgresql/data
    networks:
      - spring-cloud-network


networks:
  spring-cloud-network:

volumes:
  postgvol:
